--[[
     ┏┏┓ o ┳━┓ ┓━┓ ┏┏┓ ┳━┓
     ┃┃┃ ┃ ┃━┫ ┗━┓ ┃┃┃ ┃━┫
     ┛ ┇ ┇ ┛ ┇ ━━┛ ┛ ┇ ┛ ┇
 a fog descends upon your editor
 https://github.com/xero/miasma.nvim

 Lua port of the miasma colorscheme for Neovim.
 Place this file at:  colors/miasma.lua
 Then load it with:   :colorscheme miasma
 or from Lua:         vim.cmd.colorscheme("miasma")
]]

-- reset any existing highlighting / clear syntax
if vim.g.colors_name then
  vim.cmd("hi clear")
end
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.opt.background = "dark"
vim.g.colors_name = "miasma"

local hl = vim.api.nvim_set_hl

-- base highlight groups -----------------------------------------------
local groups = {
  ["Boolean"] = { fg = "#78834b" },
  ["ColorColumn"] = { bg = "#222222" },
  ["Comment"] = { fg = "#666666" },
  ["Constant"] = { fg = "#bb7744" },
  ["CursorColumn"] = { bg = "#1c1c1c" },
  ["Cursor"] = { fg = "#222222", bg = "#685742" },
  ["CursorLine"] = { bg = "#1c1c1c" },
  ["CursorLineNr"] = { fg = "#78824b", bg = "#1c1c1c", bold = true },
  ["Delimiter"] = { fg = "#d7c483" },
  ["DiagnosticDeprecated"] = { sp = "#685742", strikethrough = true },
  ["DiagnosticError"] = { fg = "#b36d43" },
  ["DiagnosticHintFloating"] = { fg = "#78824b" },
  ["DiagnosticHint"] = { fg = "#5f875f" },
  ["DiagnosticInfo"] = { fg = "#5f875f" },
  ["DiagnosticOk"] = { fg = "#78824b" },
  ["DiagnosticSignError"] = { fg = "#b36d43", bg = "#1c1c1c" },
  ["DiagnosticSignHint"] = { fg = "#5f875f", bg = "#1c1c1c" },
  ["DiagnosticSignInfo"] = { fg = "#78824b", bg = "#1c1c1c" },
  ["DiagnosticSignWarn"] = { fg = "#685742", bg = "#1c1c1c" },
  ["DiagnosticUnderlineError"] = { underline = true },
  ["DiagnosticUnderlineHint"] = { underline = true },
  ["DiagnosticUnderlineInfo"] = { underline = true },
  ["DiagnosticUnderlineOk"] = { underline = true },
  ["DiagnosticUnderlineWarn"] = { underline = true },
  ["DiagnosticUnnecessary"] = { fg = "#666666", underline = true },
  ["DiagnosticVirtualTextError"] = { fg = "#b36d43" },
  ["DiagnosticVirtualTextHint"] = { fg = "#78824b", bg = "#222222" },
  ["DiagnosticVirtualTextInfo"] = { fg = "#78824b", bg = "#222222" },
  ["DiagnosticVirtualTextWarn"] = { fg = "#685742", bg = "#222222" },
  ["DiagnosticVirtualTextWarning"] = { fg = "#d7c483" },
  ["DiagnosticWarn"] = { fg = "#685742" },
  ["DiagnosticWarningFloating"] = { fg = "#d7c483" },
  ["DiagnosticWarning"] = { fg = "#b36d43" },
  ["DiffAdded"] = { fg = "#5f875f", bg = "#1c1c1c" },
  ["DiffAdd"] = { fg = "#222222", bg = "#5f875f" },
  ["DiffChange"] = { fg = "#222222", bg = "#685742" },
  ["DiffDelete"] = { fg = "#222222", bg = "#b36d43", bold = true },
  ["DiffRemoved"] = { fg = "#b36d43", bg = "#1c1c1c" },
  ["DiffText"] = { fg = "#222222", bg = "#c9a554", bold = true },
  ["Directory"] = { fg = "#78824b", bg = "#1c1c1c" },
  ["Error"] = { fg = "#c2c2b0", bg = "#bb7744" },
  ["ErrorMsg"] = { fg = "#b36d43", bg = "#222222" },
  ["FloatShadow"] = { bg = "#101010" },
  ["FloatShadowThrough"] = { bg = "#151515" },
  ["FoldColumn"] = { fg = "#666666", bg = "#1c1c1c" },
  ["Folded"] = { fg = "#b36d43", bg = "#1c1c1c" },
  ["Function"] = { fg = "#78834b" },
  ["gitCommitBranch"] = { fg = "#b36d43" },
  ["gitCommitSelectedFile"] = { fg = "#5f875f" },
  ["gitCommitSelectedType"] = { fg = "#5f875f" },
  ["gitCommitUnmergedFile"] = { fg = "#685742" },
  ["gitCommitUnmergedType"] = { fg = "#685742" },
  ["GitSignsAdd"] = { fg = "#5f875f", bg = "#1c1c1c" },
  ["GitSignsChange"] = { fg = "#685742", bg = "#1c1c1c" },
  ["GitSignsDelete"] = { fg = "#b36d43", bg = "#1c1c1c" },
  ["htmlArg"] = { fg = "#5f875f" },
  ["htmlBold"] = { bold = true },
  ["htmlBoldItalic"] = { bold = true, underline = true },
  ["htmlBoldUnderline"] = { bold = true, underline = true },
  ["htmlBoldUnderlineItalic"] = { bold = true, underline = true },
  ["htmlH1"] = { bold = true },
  ["htmlItalic"] = { underline = true },
  ["htmlTag"] = { fg = "#5f875f" },
  ["htmlTagName"] = { fg = "#5f875f" },
  ["htmlUnderline"] = { underline = true },
  ["htmlUnderlineItalic"] = { underline = true },
  ["IblIndent"] = { fg = "#242d1d", nocombine = true },
  ["IblScope"] = { fg = "#43492a", nocombine = true },
  ["IblWhitespace"] = { fg = "#242d1d", nocombine = true },
  ["Identifier"] = { fg = "#d7c483" },
  ["Ignore"] = { fg = "#444444", underline = true },
  ["IncSearch"] = { fg = "#222222", bg = "#bb7744" },
  ["Keyword"] = { fg = "#5f875f" },
  ["LazyButtonActive"] = { fg = "#222222", bg = "#78834b" },
  ["LazyButton"] = { bg = "#222222" },
  ["LazyComment"] = {},
  ["LazyCommit"] = {},
  ["LazyCommitIssue"] = {},
  ["LazyCommitScope"] = {},
  ["LazyCommitType"] = {},
  ["LazyDimmed"] = {},
  ["LazyDir"] = {},
  ["LazyH1"] = { fg = "#78834b", bg = "#222222" },
  ["LazyH2"] = { fg = "#78834b", bg = "#222222" },
  ["LazyLocal"] = {},
  ["LazyNoCond"] = {},
  ["LazyNormal"] = { bg = "#1c1c1c" },
  ["LazyProgressDone"] = {},
  ["LazyProgressTodo"] = {},
  ["LazyProp"] = {},
  ["LazyReasonCmd"] = {},
  ["LazyReasonEvent"] = {},
  ["LazyReasonFt"] = {},
  ["LazyReasonImport"] = {},
  ["LazyReasonKeys"] = {},
  ["LazyReasonPlugin"] = {},
  ["LazyReasonRuntime"] = {},
  ["LazyReasonSource"] = {},
  ["LazyReasonStart"] = {},
  ["LazySpecial"] = { fg = "#c9a554" },
  ["LazyTaskError"] = {},
  ["LazyTaskOutput"] = {},
  ["LazyUrl"] = {},
  ["LazyValue"] = {},
  ["lCursor"] = { fg = "bg", bg = "fg" },
  ["lessVariable"] = { fg = "#b36d43" },
  ["LineNr"] = { fg = "#666666", bg = "#1c1c1c" },
  ["LspBorderBG"] = { fg = "#685742", bg = "#222222" },
  ["LspFloatWinNormal"] = { fg = "#d7c483", bg = "#43492a" },
  ["LspReferenceRead"] = { fg = "#5f875f", sp = "#fd9720", bold = true, undercurl = true },
  ["LspReferenceText"] = { fg = "#d7c483", bg = "#43492a", sp = "#fd9720", bold = true, undercurl = true },
  ["LspReferenceWrite"] = { fg = "#5f875f", sp = "#fd9720", bold = true, undercurl = true },
  ["LspSignatureActiveParameter"] = { sp = "#fbec9f", bold = true, italic = true, underline = true },
  ["markdownBold"] = { bold = true },
  ["markdownItalic"] = { underline = true },
  ["MasonError"] = {},
  ["MasonHeader"] = { fg = "#d7c483", bg = "#1c1c1c" },
  ["MasonHeading"] = {},
  ["MasonHighlightBlockBoldSecondary"] = {},
  ["MasonHighlightBlockSecondary"] = {},
  ["MasonHighlight"] = { fg = "#78824b", bg = "#222222" },
  ["MasonHighlightSecondary"] = {},
  ["MasonMuted"] = { fg = "#c9a554", bg = "#1c1c1c" },
  ["MasonWarning"] = {},
  ["MatchParen"] = { fg = "#d7c483", bold = true, underline = true },
  ["ModeMsg"] = { bold = true },
  ["MoreMsg"] = { fg = "#5f875f", bold = true },
  ["mustacheMarker"] = { fg = "#bb7744" },
  ["mustachePartial"] = { fg = "#bb7744" },
  ["mustacheSection"] = { bold = true },
  ["mustacheVariable"] = { fg = "#c9a554" },
  ["mustacheVariableUnescape"] = { fg = "#685742" },
  ["netrwClassify"] = { fg = "#666666", bold = true },
  ["netrwExe"] = { fg = "#685742" },
  ["NonText"] = { fg = "#666666", bold = true },
  ["Normal"] = { fg = "#D7C483", bg = "#222222" },
  ["Number"] = { fg = "#78824b" },
  ["NvimInternalError"] = { fg = "#1c1c1c", bg = "#b36d43" },
  ["phpIdentifier"] = { fg = "#b36d43" },
  ["phpSpecialFunction"] = { fg = "#bb7744" },
  ["Pmenu"] = { fg = "#d7c483", bg = "#1c1c1c" },
  ["PmenuSbar"] = { bg = "#666666" },
  ["PmenuSel"] = { fg = "#222222", bg = "#78834b" },
  ["PmenuThumb"] = { fg = "#d7c483", bg = "#d7c483" },
  ["Question"] = { fg = "#5f875f", bold = true },
  ["RedrawDebugClear"] = { fg = "#222222", bg = "#c9a554" },
  ["RedrawDebugComposed"] = { fg = "#222222", bg = "#78834b" },
  ["RedrawDebugNormal"] = { reverse = true },
  ["RedrawDebugRecompose"] = { fg = "#222222", bg = "#bb7744" },
  ["ScrollbarCursor"] = { fg = "#222222" },
  ["ScrollbarCursorHandle"] = { fg = "#222222", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarError"] = { fg = "#685742" },
  ["ScrollbarErrorHandle"] = { fg = "#685742", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarGitAdd"] = { fg = "#5f875f" },
  ["ScrollbarGitAddHandle"] = { fg = "#5f875f", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarGitChange"] = { fg = "#685742" },
  ["ScrollbarGitChangeHandle"] = { fg = "#685742", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarGitDelete"] = { fg = "#b36d43" },
  ["ScrollbarGitDeleteHandle"] = { fg = "#b36d43", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarHandle"] = { bg = "#1c1c1c", blend = 0 },
  ["ScrollbarHint"] = { fg = "#5f875f" },
  ["ScrollbarHintHandle"] = { fg = "#5f875f", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarInfo"] = { fg = "#5f875f" },
  ["ScrollbarInfoHandle"] = { fg = "#5f875f", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarMisc"] = { fg = "#bb7744" },
  ["ScrollbarMiscHandle"] = { fg = "#bb7744", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarSearch"] = { fg = "#c9a554" },
  ["ScrollbarSearchHandle"] = { fg = "#c9a554", bg = "#1c1c1c", blend = 0 },
  ["ScrollbarWarn"] = { fg = "#b36d43" },
  ["ScrollbarWarnHandle"] = { fg = "#b36d43", bg = "#1c1c1c", blend = 0 },
  ["Search"] = { fg = "#222222", bg = "#5f875f" },
  ["shDerefSimple"] = { fg = "#b36d43" },
  ["SignColumn"] = { fg = "#666666", bg = "#1c1c1c" },
  ["Special"] = { fg = "#bb7744" },
  ["SpecialKey"] = { fg = "#d7c483" },
  ["SpellBad"] = { fg = "#685742", sp = "#d7c483", underline = true },
  ["SpellCap"] = { fg = "#5f875f", sp = "#d7c483", underline = true },
  ["SpellLocal"] = { fg = "#bb7744", sp = "#d7c483", underline = true },
  ["SpellRare"] = { fg = "#b36d43", sp = "#d7c483", underline = true },
  ["Statement"] = { fg = "#5f875f", bold = true },
  ["StatusLine"] = { fg = "#d7c483", bg = "#222222", bold = true },
  ["StatusLineNC"] = { fg = "#666666", bg = "#222222", bold = true },
  ["String"] = { fg = "#685742" },
  ["SyntasticErrorSign"] = { fg = "#b36d43" },
  ["SyntasticWarningSign"] = { fg = "#685742" },
  ["TabLineFill"] = { fg = "#c9a554", bg = "#222222" },
  ["TabLine"] = { fg = "#666666", bg = "#111111" },
  ["TabLineSel"] = { fg = "#111111", bg = "#78834b", bold = true },
  ["TabLineSelSep"] = { fg = "#78834b", bg = "#1c1c1c", bold = true },
  ["TabLineSep"] = { fg = "#111111", bg = "#222222" },
  ["TelescopeBorder"] = { fg = "#685742", bg = "#1c1c1c" },
  ["TelescopeMultiIcon"] = {},
  ["TelescopeMultiSelection"] = {},
  ["TelescopeNormal"] = {},
  ["TelescopePreviewBlock"] = {},
  ["TelescopePreviewCharDev"] = {},
  ["TelescopePreviewDate"] = {},
  ["TelescopePreviewDirectory"] = {},
  ["TelescopePreviewExecute"] = {},
  ["TelescopePreviewGroup"] = {},
  ["TelescopePreviewHyphen"] = {},
  ["TelescopePreviewLink"] = {},
  ["TelescopePreviewMatch"] = {},
  ["TelescopePreviewMessageFillchar"] = {},
  ["TelescopePreviewMessage"] = {},
  ["TelescopePreviewNormal"] = {},
  ["TelescopePreviewPipe"] = {},
  ["TelescopePreviewRead"] = {},
  ["TelescopePreviewSize"] = {},
  ["TelescopePreviewSocket"] = {},
  ["TelescopePreviewSticky"] = {},
  ["TelescopePreviewUser"] = {},
  ["TelescopePreviewWrite"] = {},
  ["TelescopePromptBorder"] = { fg = "#b36d43", bg = "#1c1c1c" },
  ["TelescopePromptNormal"] = {},
  ["TelescopeResultsClass"] = {},
  ["TelescopeResultsComment"] = {},
  ["TelescopeResultsConstant"] = {},
  ["TelescopeResultsDiffUntracked"] = {},
  ["TelescopeResultsField"] = {},
  ["TelescopeResultsFunction"] = {},
  ["TelescopeResultsIdentifier"] = {},
  ["TelescopeResultsLineNr"] = {},
  ["TelescopeResultsMethod"] = {},
  ["TelescopeResultsNormal"] = {},
  ["TelescopeResultsNumber"] = {},
  ["TelescopeResultsOperator"] = {},
  ["TelescopeResultsSpecialComment"] = {},
  ["TelescopeResultsStruct"] = {},
  ["TelescopeResultsVariable"] = {},
  ["TelescopeSelectionCaret"] = { fg = "#d7c483", bg = "#78824b" },
  ["TelescopeTitle"] = { fg = "#5f875f", bg = "#1c1c1c" },
  ["TermCursor"] = { reverse = true },
  ["Title"] = { fg = "#b36d43", bold = true },
  ["Todo"] = { fg = "#d7c483", bold = true, underline = true },
  ["Type"] = { fg = "#78834b", bold = true },
  ["Underlined"] = { fg = "#78834b", underline = true },
  ["User1"] = { fg = "#d7c483", bg = "#bb7744" },
  ["User2"] = { fg = "#d7c483", bg = "#666666" },
  ["User3"] = { fg = "#d7c483", bg = "#b36d43" },
  ["User4"] = { fg = "#d7c483", bg = "#222222" },
  ["User5"] = { fg = "#d7c483", bg = "#bb7744" },
  ["User6"] = { fg = "#d7c483", bg = "#c9a554" },
  ["User7"] = { fg = "#d7c483", bg = "#78824b" },
  ["User8"] = { fg = "#d7c483", bg = "#b36d43" },
  ["User9"] = { fg = "#d7c483", bg = "#666666" },
  ["VertSplit"] = { fg = "#1c1c1c", bg = "#222222" },
  ["Visual"] = { fg = "#222222", bg = "#78824b" },
  ["WarningMsg"] = { fg = "#b36d43" },
  ["WhichKeyBorder"] = { bg = "#1c1c1c" },
  ["WhichKeyDesc"] = { fg = "#5f875f", bg = "#1c1c1c" },
  ["WhichKeyFloat"] = { bg = "#1c1c1c" },
  ["WhichKeyGroup"] = { bg = "#1c1c1c" },
  ["WhichKey"] = { fg = "#d7c483", bg = "#1c1c1c" },
  ["WhichKeySeparator"] = { fg = "#c9a554", bg = "#1c1c1c" },
  ["WhichKeyValue"] = { fg = "#c9a554" },
  ["WildMenu"] = { fg = "black", bg = "#c9a554" },
  ["WinBar"] = { bold = true },
  ["xmlTag"] = { fg = "#78824b" },
  ["xmlTagName"] = { fg = "#78834b" },
}

for group, opts in pairs(groups) do
  hl(0, group, opts)
end

-- linked highlight groups ----------------------------------------------
local links = {
  ["@boolean"] = "Boolean",
  ["Character"] = "Constant",
  ["@comment"] = "Comment",
  ["Conceal"] = "Ignore",
  ["Conditional"] = "Statement",
  ["@constant.builtin"] = "Special",
  ["@constant"] = "Constant",
  ["@constructor"] = "Special",
  ["CtrlPLinePre"] = "Comment",
  ["CtrlPMatch"] = "String",
  ["CurSearch"] = "Search",
  ["CursorLineFold"] = "FoldColumn",
  ["CursorLineSign"] = "SignColumn",
  ["Debug"] = "Special",
  ["Define"] = "PreProc",
  ["DiagnosticErrorFloating"] = "DiagnosticError",
  ["DiagnosticFloatingError"] = "DiagnosticError",
  ["DiagnosticFloatingHint"] = "DiagnosticHint",
  ["DiagnosticFloatingInfo"] = "DiagnosticInfo",
  ["DiagnosticFloatingOk"] = "DiagnosticOk",
  ["DiagnosticFloatingWarn"] = "DiagnosticWarn",
  ["DiagnosticFloatingWarning"] = "DiagnosticWarning",
  ["DiagnosticSignOk"] = "DiagnosticOk",
  ["DiagnosticVirtualTextOk"] = "DiagnosticOk",
  ["EndOfBuffer"] = "NonText",
  ["Exception"] = "Statement",
  ["@field"] = "Identifier",
  ["Float"] = "Number",
  ["FloatTitle"] = "Title",
  ["@function.builtin"] = "Special",
  ["@function"] = "Function",
  ["FzfLuaBorder"] = "Normal",
  ["FzfLuaCursor"] = "Cursor",
  ["FzfLuaCursorLine"] = "CursorLine",
  ["FzfLuaCursorLineNr"] = "CursorLineNr",
  ["FzfLuaNormal"] = "Normal",
  ["FzfLuaScrollFloatEmpty"] = "PmenuSbar",
  ["FzfLuaScrollFloatFull"] = "PmenuThumb",
  ["FzfLuaSearch"] = "IncSearch",
  ["gitCommitDiscardedFile"] = "gitCommitUnmergedFile",
  ["gitCommitDiscardedType"] = "gitCommitUnmergedType",
  ["gitCommitFile"] = "Directory",
  ["gitCommitUntrackedFile"] = "gitCommitUnmergedFile",
  ["helpExample"] = "String",
  ["helpHeadline"] = "Title",
  ["helpHyperTextEntry"] = "Statement",
  ["helpHyperTextJump"] = "Underlined",
  ["helpSectionDelim"] = "Comment",
  ["helpURL"] = "Underlined",
  ["htmlEndTag"] = "htmlTag",
  ["htmlLink"] = "Underlined",
  ["Include"] = "PreProc",
  ["javaScriptBraces"] = "Delimiter",
  ["javaScript"] = "Normal",
  ["@keyword"] = "Keyword",
  ["Label"] = "Statement",
  ["lessVariableValue"] = "Normal",
  ["LineNrAbove"] = "LineNr",
  ["LineNrBelow"] = "LineNr",
  ["LspCodeLens"] = "Comment",
  ["@lsp.type.comment"] = "Comment",
  ["@lsp.type.decorator"] = "Function",
  ["@lsp.type.enumMember"] = "Constant",
  ["@lsp.type.function"] = "Function",
  ["@lsp.type.method"] = "Function",
  ["@lsp.type.parameter"] = "Identifier",
  ["@lsp.type.property"] = "Identifier",
  ["@lsp.type.type"] = "Type",
  ["@lsp.type.variable"] = "Identifier",
  ["Macro"] = "PreProc",
  ["markdownCodeBlock"] = "String",
  ["markdownCodeDelimiter"] = "NonText",
  ["markdownHeadingRule"] = "NonText",
  ["markdownLinkDelimiter"] = "Delimiter",
  ["markdownURLDelimiter"] = "Delimiter",
  ["MasonHeaderSecondary"] = "LazyButtonActive",
  ["MasonHighlightBlockBold"] = "LazyButtonActive",
  ["MasonHighlightBlock"] = "LazyButtonActive",
  ["MasonMutedBlockBold"] = "MasonHighlight",
  ["MasonMutedBlock"] = "MasonMuted",
  ["@method"] = "Function",
  ["MsgSeparator"] = "StatusLine",
  ["@namespace"] = "Identifier",
  ["NERDTreeExecFile"] = "String",
  ["NERDTreeHelp"] = "Comment",
  ["NormalFloat"] = "Pmenu",
  ["@number"] = "Number",
  ["NvimArrow"] = "Delimiter",
  ["NvimColon"] = "Delimiter",
  ["NvimComma"] = "Delimiter",
  ["NvimFigureBrace"] = "NvimInternalError",
  ["NvimIdentifier"] = "Identifier",
  ["NvimInvalid"] = "Error",
  ["NvimInvalidSingleQuotedUnknownEscape"] = "NvimInternalError",
  ["NvimInvalidSpacing"] = "ErrorMsg",
  ["NvimNumber"] = "Number",
  ["NvimNumberPrefix"] = "Type",
  ["NvimOptionSigil"] = "Type",
  ["NvimParenthesis"] = "Delimiter",
  ["NvimSingleQuotedUnknownEscape"] = "NvimInternalError",
  ["NvimSpacing"] = "Normal",
  ["NvimString"] = "String",
  ["Operator"] = "Delimiter",
  ["@parameter"] = "Identifier",
  ["phpDefine"] = "Statement",
  ["phpHereDoc"] = "String",
  ["phpVarSelector"] = "phpIdentifier",
  ["PmenuExtra"] = "Pmenu",
  ["PmenuExtraSel"] = "PmenuSel",
  ["PmenuKind"] = "Pmenu",
  ["PmenuKindSel"] = "PmenuSel",
  ["PreCondit"] = "PreProc",
  ["PreProc"] = "Keyword",
  ["@preproc"] = "PreProc",
  ["@property"] = "Identifier",
  ["@punctuation"] = "Delimiter",
  ["QuickFixLine"] = "Search",
  ["Repeat"] = "Statement",
  ["rubyConstant"] = "Constant",
  ["rubyDefine"] = "Statement",
  ["rubyInstanceVariable"] = "Number",
  ["rubyLocalVariableOrMethod"] = "Identifier",
  ["shDerefVar"] = "shDerefSimple",
  ["SpecialChar"] = "Special",
  ["SpecialComment"] = "Special",
  ["StorageClass"] = "Type",
  ["@string"] = "String",
  ["Structure"] = "Type",
  ["Substitute"] = "Search",
  ["Tag"] = "Special",
  ["TelescopeMatching"] = "Special",
  ["TelescopePreviewBorder"] = "TelescopeBorder",
  ["TelescopePreviewLine"] = "TelescopeSelection",
  ["TelescopePreviewTitle"] = "TelescopeTitle",
  ["TelescopePromptCounter"] = "TelescopeBorder",
  ["TelescopePromptPrefix"] = "TelescopeTitle",
  ["TelescopePromptTitle"] = "TelescopeTitle",
  ["TelescopeResultsBorder"] = "TelescopeBorder",
  ["TelescopeResultsFileIcon"] = "Special",
  ["TelescopeResultsTitle"] = "TelescopeTitle",
  ["TelescopeSelection"] = "Visual",
  ["@text.diff.add"] = "DiffAdd",
  ["@text.diff.delete"] = "DiffDelete",
  ["@text.literal"] = "Comment",
  ["@text.reference"] = "Identifier",
  ["@text.title"] = "Title",
  ["@text.todo"] = "Todo",
  ["@text.underline"] = "Underlined",
  ["@text.uri"] = "Underlined",
  ["Typedef"] = "Type",
  ["@type"] = "Type",
  ["@variable"] = "Identifier",
  ["vimContinue"] = "Delimiter",
  ["vimHiAttrib"] = "Constant",
  ["vimSetSep"] = "Delimiter",
  ["Whitespace"] = "NonText",
  ["WinBarNC"] = "WinBar",
  ["WinSeparator"] = "VertSplit",
  ["xmlAttrib"] = "xmlTag",
  ["xmlEndTag"] = "xmlTag",
  ["xmlEqual"] = "xmlTag",
  ["xmlString"] = "xmlTagName",
}

for from, to in pairs(links) do
  hl(0, from, { link = to })
end

